### ISSUE TITLE
已使用“.NETFramework,Version=v4.6.1”而不是项目目标框架“.NETCoreApp,Version=v2.2”还原包“log4stash 2.2.1”。此包可能与项目不完全兼容

### ISSUE THREAD

**Issue by murongqingsi** [urielha/log4stash#56] opened 2019-09-01 12:41 UTC

**Comment by urielha** [comment] 2020-01-08 11:46
Known issue.
I will appreciate some help with that.

duplicate of issue: #54 

And apparently I can read Chinese now with Google translate :)

**Closed as completed** 2020-01-08 11:47 UTC
